[package]
name = "version-history-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
chu-liu-edmonds = "0.1.0"
clap = { version = "4.5.24", features = ["cargo"] }
ndarray = "0.15"
render_as_tree = "0.2.1"
similar = "2.6.0"
